config/routes.rb
SocialThingamajig::Application.routes.draw do

  resources :users do
    get 'reset_password'
    get 'feed'
  end
  resource :session
  get 'forgot_password', controller: :users
  post 'generate_reset_password', controller: :users

  resources :friend_circles
  resources :posts

end

app/models/friend_circle.rb
# == Schema Information
#
# Table name: friend_circles
#
#  id         :integer          not null, primary key
#  owner_id   :integer          not null
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FriendCircle < ActiveRecord::Base
  attr_accessible :owner_id, :name, :member_ids

  validates :owner_id, presence: true

  has_many :memberships,
           :foreign_key => :friend_circle_id,
           :primary_key => :id,
           :class_name => "FriendCircleMembership",
           :inverse_of => :friend_circle

  has_many :members,
           :through => :memberships,
           :source => :member

  belongs_to :owner,
             :foreign_key => :owner_id,
             :primary_key => :id,
             :class_name => "User"

  has_many :post_shares,
           :foreign_key => :friend_circle_id,
           :primary_key => :id,
           :class_name => "PostShare"
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController

  def new
    @friend_circle = FriendCircle.new
    @users = User.all

    render :new
  end

  def create
    @friend_circle = FriendCircle.new(params[:friend_circle])
    @friend_circle.owner_id = current_user.id

    if @friend_circle.save
      redirect_to friend_circle_url(@friend_circle)
    else
      flash[:errors] = @friend_circle.errors.full_messages
      redirect_to new_friend_circle_url
    end
  end

  def index

  end

  def show
    @friend_circle = FriendCircle.includes(:members).find(params[:id])

    render :show
  end

  def edit
    @friend_circle = FriendCircle.includes(:members).find(params[:id])
    @users = User.all

    render :edit
  end

  def update
    @friend_circle = FriendCircle.find(params[:id])
    if @friend_circle.update_attributes(params[:friend_circle])
      redirect_to friend_circle_url(@friend_circle)
    else
      flash[:errors] = @friend_circle.errors.full_messages
      redirect_to edit_friend_circle_url(@friend_circle)
    end
  end

  def destroy

  end
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/views/friend_circles/_form.html.erb
<form action=<%= path %> method="POST">
  <% if friend_circle.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>
  <input type="hidden" name="friend_circle[member_ids][]" value="">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Friend circle name:
    <input type="text" name="friend_circle[name]" value=<%= friend_circle.name %>>
  </label>

  <br>
  Who do you want to add to this Friend Circle?

    <% users.each do |user| %>
    <% html_id = "friend_circle_member_ids_#{user.id}" %>
      <br>

      <% unless current_user == user %>
        <input
          type="checkbox"
          name="friend_circle[member_ids][]"
          value="<%= user.id %>"
          id="<%= html_id %>"
          <%= friend_circle.members.include?(user) ? "checked" : "" %>>
        <label for="<%= html_id %>">
          <%= user.email %>
        </label>
      <% end %>

    <% end %>



  <br>
  <input type="submit" value="Create friend circle!">

</form>

app/views/friend_circles/edit.html.erb
<%= render "form", path: friend_circle_url(@friend_circle), friend_circle: @friend_circle, users: @users %>

app/views/friend_circles/new.html.erb
<h1>Create a new friend circle!</h1>
<%= render "form", path: friend_circles_url, friend_circle: @friend_circle, users: @users %>

app/views/friend_circles/show.html.erb
<h1>Friend Circle: <%= @friend_circle.name %></h1>
<br>
<h2>Friends:</h2>
<% @friend_circle.members.each do |member| %>

<%= member.email %>
<br>

<% end %>