config/routes.rb
SocialThingamajig::Application.routes.draw do

  resources :users do
    get 'reset_password'
    get 'feed'
  end
  resource :session
  get 'forgot_password', controller: :users
  post 'generate_reset_password', controller: :users

  resources :friend_circles
  resources :posts

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password

  before_validation(:ensure_session_token)

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  has_many :friend_circles,
           :foreign_key => :owner_id,
           :primary_key => :id,
           :class_name => "FriendCircle"

  has_many :friend_circle_memberships,
           :foreign_key => :member_id,
           :primary_key => :id,
           :class_name => "FriendCircleMembership"

  has_many :friends,
           :through => :friend_circles,
           :source => :members

  has_many :posts,
           :foreign_key => :user_id,
           :primary_key => :id,
           :class_name => "Post",
           :inverse_of => :author

  def feed_posts

    Post.joins(:post_shares).joins("JOIN friend_circle_memberships ON post_shares.friend_circle_id = friend_circle_memberships.friend_circle_id")
        .joins("JOIN users ON friend_circle_memberships.member_id = users.id")
        .where("users.id = ?", self.id).includes(:links).includes(:author)

  end

  def self.find_by_credentials(email, password)
    @user = User.find_by_email(email)

    (@user && @user.is_password?(password)) ? @user : nil

  end

  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])
    @user.posts.new(params[:post])
    @post = @user.posts.first
    link_attributes = params[:link_attributes].values.reject { |link| link["url"].empty? }
    @post.links.new(link_attributes)

    if @user.save
      self.login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def new
    @user = User.new
    @post = Post.new
    3.times { @post.links.build }

    render :new
  end

  def show
    @user = User.find(params[:id])
  end

  def feed
    @user = User.find(params[:user_id])
    @feed_posts = @user.feed_posts
  end

  def forgot_password
    render :enter_email
  end

  def generate_reset_password
    @user = User.find_by_email(params[:user][:email])
    random_password = SecureRandom.urlsafe_base64
    @user.password = random_password
    @user.save!
    msg = UserMailer.password_reset_email(@user, random_password)
    msg.deliver!
    render :check_email
  end

  def reset_password
    @user = User.find(params[:user_id])

    if @user.is_password?(params[:password])
      render :edit
    else
      flash[:errors] = ["Failed password reset! Please contact us."]
      redirect_to new_session_url
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      self.login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to user_reset_password_url(@user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_login_form.html.erb
<form action=<%= path %> method="POST">

  <% if user.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>

  <label>Email:
    <input type="text" name="user[email]" value=<%= user.email %>>
  </label>

  <br>
  <label>Password:
    <input type="password" name="user[password]" value=<%= user.password %>>
  </label>

  <br>
  <input type="submit" value="Sign In!">

</form>

app/views/users/check_email.html.erb
<h1>Password Reset</h1>
<p>We have sent you an email with a link to reset your password.  Please check your email and follow the link to reset your password.  If you don't receive the email please contact us at fake_support@example.com </p>

app/views/users/edit.html.erb
<h1>Reset Password</h1>
Please enter a new password!

<form action=<%= user_url(@user) %> method="POST">
  <input type="hidden" name="_method" value="PUT">

  <p>Email:<%= @user.email %></p>

  <br>
  <label>New Password:
    <input type="password" name="user[password]">
  </label>

  <br>
  <input type="submit" value="create new password">

</form>

app/views/users/enter_email.html.erb
<h1>Forgot Password</h1>
please enter your email to reset your password
<form action=<%= generate_reset_password_url %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
  <label>Email:
    <input type="text" name="user[email]">
  </label>
  <br>
  <input type="submit" value="Reset Password">
</form>

app/views/users/feed.html.erb
<h1>My feed</h1>

<% @feed_posts.each do |feed_post| %>
Author:
<%= feed_post.author.email %>
<br>
Description:
<%= feed_post.body %>
<ul>
<% feed_post.links.each do |link| %>
<li><a href=<%= link.url %>><%= link.url %></a></li>
<% end %>
</ul>
<% end %>

app/views/users/new.html.erb
<h1> Sign up! </h1>

<form action=<%= users_url %> method="POST">

  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>

  <label>Email:
    <input type="text" name="user[email]" value=<%= @user.email %>>
  </label>

  <br>
  <label>Password:
    <input type="password" name="user[password]">
  </label>

  <br>


<h3>Create Your First Post!</h3>

  <label for="post_body">Description of Links:</label> <br>
<textarea rows="4" cols="40" value="<%= @post.body %>" name="post[body]" id="post_body">
</textarea>

  <br>

  <% @post.links.each do |link| %>
    <label>Link:
    <input name="link_attributes[<%= link.object_id %>][url]">
    </label>
    <br>
  <% end %>
  <br>
  <input type="submit" value="Create my account!">

</form>

app/views/users/show.html.erb
<h1> My Profile </h1>

<%= current_user.email %>