config/routes.rb
SocialThingamajig::Application.routes.draw do

  resources :users do
    get 'reset_password'
    get 'feed'
  end
  resource :session
  get 'forgot_password', controller: :users
  post 'generate_reset_password', controller: :users

  resources :friend_circles
  resources :posts

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :user_id, :body, :friend_circle_ids

  validates :author, :body, presence: true

  belongs_to :author,
  :foreign_key => :user_id,
  :primary_key => :id,
  :class_name => "User"

  has_many :post_shares,
  :foreign_key => :post_id,
  :primary_key => :id,
  :class_name => "PostShare",
  :inverse_of => :post

  has_many :friend_circles,
  :through => :post_shares,
  :source => :friend_circle

  has_many :links,
  :foreign_key => :post_id,
  :primary_key => :id,
  :class_name => "Link",
  :inverse_of => :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    3.times { @post.links.build }

    @friend_circles = current_user.friend_circles

    render :new
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    link_attributes = params[:link_attributes].values.reject { |link| link["url"].empty? }
    @post.links.new(link_attributes)

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def show
    @post = Post.includes(:links).find(params[:id])
    render :show
  end

  def index

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/new.html.erb
<h1>Create a New Post</h1>
<form action=<%= posts_url %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>

  <label for="post_body">Description of Links:</label> <br>
<textarea rows="4" cols="40" value="<%= @post.body %>" name="post[body]" id="post_body">
</textarea>

  <br>

  <% @post.links.each do |link| %>
    <label>Link:
    <input name="link_attributes[<%= link.object_id %>][url]">
    </label>
    <br>
  <% end %>

  <br>
  Who do you want to share this post with?

  <% @friend_circles.each do |friend_circle| %>
  <% html_id = "friend_circle_ids_#{friend_circle.id}" %>
    <br>

      <input
        type="checkbox"
        name="post[friend_circle_ids][]"
        value="<%= friend_circle.id %>"
        id="<%= html_id %>">

      <label for="<%= html_id %>">
        <%= friend_circle.name %>
      </label>

  <% end %>



<br>

  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h1>Post # <%= @post.id %></h1>
<%= @post.body %>
<br>
<ul>
  <% @post.links.each do |link| %>
    <li><a href="<%= link.url %>"><%= link.url %></a></li>
  <% end %>
</ul>